# Generated by Django 2.1.1 on 2018-09-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.CharField(choices=[(1, 'em estoque'), (2, 'sem estoque'), (3, 'desativado')], default=1, max_length=2)),
            ],
        ),
    ]
