# Generated by Django 2.1.1 on 2018-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[(1, 'em estoque'), (2, 'sem estoque'), (3, 'desativado')], default=1, max_length=1),
        ),
    ]
