# Generated by Django 2.1.1 on 2018-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180908_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.IntegerField(choices=[(1, 'em estoque'), (2, 'sem estoque'), (3, 'desativado')], default=1),
        ),
    ]
