# Generated by Django 4.1.5 on 2023-09-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180908_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Lista de Produtos'},
        ),
    ]
